import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { InfoIcon } from './icons/InfoIcon';
import { XIcon } from './icons/XIcon';

interface DisclaimerModalProps {
  isOpen: boolean;
  onAccept: () => void;
  onClose: () => void;
}

export const DisclaimerModal: React.FC<DisclaimerModalProps> = ({ isOpen, onAccept, onClose }) => {
  const acceptButtonRef = React.useRef<HTMLButtonElement>(null);
  
  React.useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };
    
    if (isOpen) {
      document.addEventListener('keydown', handleKeyDown);
      // When the modal opens, move focus to the primary action button.
      // A short timeout ensures the element is rendered and focusable.
      setTimeout(() => {
        acceptButtonRef.current?.focus();
      }, 100);
    }

    return () => {
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [isOpen, onClose]);

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.3 }}
          className="fixed inset-0 bg-background/80 backdrop-blur-sm flex items-center justify-center p-4 z-50"
          onClick={onClose}
        >
          <motion.div
            initial={{ scale: 0.95, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.95, opacity: 0 }}
            transition={{ type: 'spring', stiffness: 400, damping: 30 }}
            className="glass-panel p-8 max-w-lg w-full relative rounded-2xl border-border"
            onClick={(e) => e.stopPropagation()} // Prevent closing when clicking inside the modal
            role="dialog"
            aria-modal="true"
            aria-labelledby="disclaimer-title"
          >
            <button 
              onClick={onClose} 
              className="absolute top-4 right-4 text-muted-foreground hover:text-foreground transition-colors"
              aria-label="Close disclaimer"
            >
              <XIcon className="w-5 h-5" />
            </button>
            <div className="flex items-center gap-3">
              <InfoIcon className="w-6 h-6 text-primary" />
              <h2 id="disclaimer-title" className="text-2xl font-bold font-serif">Before You Proceed</h2>
            </div>
            <p className="mt-4 text-muted-foreground">
              ClaroClause is an AI-powered tool designed to provide simplified explanations of complex texts. It is not a substitute for professional legal advice.
            </p>
            <ul className="mt-4 space-y-2 text-sm text-muted-foreground list-disc list-inside">
              <li>The analysis is generated by an AI and may contain inaccuracies.</li>
              <li>This tool does not constitute a lawyer-client relationship.</li>
              <li>Always consult with a qualified legal professional for important matters.</li>
            </ul>
            <div className="mt-6 flex justify-end">
              <button
                ref={acceptButtonRef}
                onClick={onAccept}
                className="px-6 py-2 bg-primary text-primary-foreground font-semibold rounded-full hover:bg-primary/90 transition-colors"
              >
                I Understand and Accept
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};